DEFAULT_BOT_CONFIG = {
    "system_instruction": None,
    "model": "gemini-3.5-flash-lite",
    "max_output_tokens": 1024,
    "thinking_level": None,
    "thinking_summaries": None,
    "tool_choice": None,
    "seed": None,
    "stop_sequences": None,
}

botshop = [
    {
        "name": "📜 Custom Brain Voucher",
        "price": 5000000,
        "description": "Re-write Ok Bot's entire system instruction. You'll pass the new prompt as the `value` when you use it.",
        "usemsg": "Ok Bot's brain has been rewritten. It can never unsee that.",
        "config": {"type": "system_instruction", "mode": "prompt"},
    },
    {
        "name": "🧹 Default Brain Reset",
        "price": 250000,
        "description": "Restore Ok Bot's default personality and system instruction.",
        "usemsg": "Ok Bot's default brain has been restored.",
        "config": {"type": "system_instruction", "mode": "reset"},
    },
    {
        "name": "🚀 Model Upgrade: 2.5 Flash Lite",
        "price": 100000,
        "description": "Set Ok Bot's model to gemini-2.5-flash-lite (the cheapest brain in town).",
        "usemsg": "Model set to gemini-2.5-flash-lite.",
        "config": {"type": "model", "value": "gemini-2.5-flash-lite"},
    },
    {
        "name": "🚀 Model Upgrade: 3.1 Flash Lite",
        "price": 250000,
        "description": "Set Ok Bot's model to gemini-3.1-flash-lite (cheap and snappy).",
        "usemsg": "Model set to gemini-3.1-flash-lite.",
        "config": {"type": "model", "value": "gemini-3.1-flash-lite"},
    },
    {
        "name": "🚀 Model Upgrade: 3.5 Flash Lite",
        "price": 500000,
        "description": "Set Ok Bot's model to gemini-3.5-flash-lite (fast, cheap, the default).",
        "usemsg": "Model set to gemini-3.5-flash-lite.",
        "config": {"type": "model", "value": "gemini-3.5-flash-lite"},
    },
    {
        "name": "🚀 Model Upgrade: 2.5 Flash",
        "price": 500000,
        "description": "Set Ok Bot's model to gemini-2.5-flash (the affordable workhorse).",
        "usemsg": "Model set to gemini-2.5-flash.",
        "config": {"type": "model", "value": "gemini-2.5-flash"},
    },
    {
        "name": "🚀 Model Upgrade: 3.7 Flash",
        "price": 1000000,
        "description": "Set Ok Bot's model to gemini-3.7-flash (newest flash, on a launch discount).",
        "usemsg": "Model set to gemini-3.7-flash.",
        "config": {"type": "model", "value": "gemini-3.7-flash"},
    },
    {
        "name": "🚀 Model Upgrade: 3.6 Flash",
        "price": 2000000,
        "description": "Set Ok Bot's model to gemini-3.6-flash (capable flash tier).",
        "usemsg": "Model set to gemini-3.6-flash.",
        "config": {"type": "model", "value": "gemini-3.6-flash"},
    },
    {
        "name": "🚀 Model Upgrade: 3.5 Flash",
        "price": 2500000,
        "description": "Set Ok Bot's model to gemini-3.5-flash (pricey flash, big brain).",
        "usemsg": "Model set to gemini-3.5-flash.",
        "config": {"type": "model", "value": "gemini-3.5-flash"},
    },
    {
        "name": "🚀 Model Upgrade: 2.5 Pro",
        "price": 2500000,
        "description": "Set Ok Bot's model to gemini-2.5-pro (the most expensive brain in the shop).",
        "usemsg": "Model set to gemini-2.5-pro.",
        "config": {"type": "model", "value": "gemini-2.5-pro"},
    },
    {
        "name": "🔋 Output Boost I",
        "price": 250000,
        "description": "Raise the max output tokens to 2048.",
        "usemsg": "Max output tokens set to 2048.",
        "config": {"type": "max_output_tokens", "value": 2048},
    },
    {
        "name": "🔋 Output Boost II",
        "price": 1000000,
        "description": "Raise the max output tokens to 4096.",
        "usemsg": "Max output tokens set to 4096.",
        "config": {"type": "max_output_tokens", "value": 4096},
    },
    {
        "name": "🔋 Output Boost III",
        "price": 4000000,
        "description": "Raise the max output tokens to 8192.",
        "usemsg": "Max output tokens set to 8192.",
        "config": {"type": "max_output_tokens", "value": 8192},
    },
    {
        "name": "🧠 Thinking Level: Minimal",
        "price": 50000,
        "description": "Set the model's thinking level to minimal.",
        "usemsg": "Thinking level set to minimal.",
        "config": {"type": "thinking_level", "value": "minimal"},
    },
    {
        "name": "🧠 Thinking Level: Low",
        "price": 50000,
        "description": "Set the model's thinking level to low.",
        "usemsg": "Thinking level set to low.",
        "config": {"type": "thinking_level", "value": "low"},
    },
    {
        "name": "🧠 Thinking Level: Medium",
        "price": 50000,
        "description": "Set the model's thinking level to medium.",
        "usemsg": "Thinking level set to medium.",
        "config": {"type": "thinking_level", "value": "medium"},
    },
    {
        "name": "🧠 Thinking Level: High",
        "price": 50000,
        "description": "Set the model's thinking level to high.",
        "usemsg": "Thinking level set to high.",
        "config": {"type": "thinking_level", "value": "high"},
    },
    {
        "name": "💭 Thinking Summaries: Auto",
        "price": 50000,
        "description": "Let the model decide whether to include thought summaries.",
        "usemsg": "Thinking summaries set to auto.",
        "config": {"type": "thinking_summaries", "value": "auto"},
    },
    {
        "name": "💭 Thinking Summaries: None",
        "price": 50000,
        "description": "Disable thought summaries.",
        "usemsg": "Thinking summaries set to none.",
        "config": {"type": "thinking_summaries", "value": "none"},
    },
    {
        "name": "🧰 Tool Choice: Auto",
        "price": 50000,
        "description": "Let the model decide whether to use tools.",
        "usemsg": "Tool choice set to auto.",
        "config": {"type": "tool_choice", "value": "auto"},
    },
    {
        "name": "🧰 Tool Choice: Any",
        "price": 50000,
        "description": "Force the model to use tools whenever possible.",
        "usemsg": "Tool choice set to any.",
        "config": {"type": "tool_choice", "value": "any"},
    },
    {
        "name": "🧰 Tool Choice: None",
        "price": 50000,
        "description": "Disable tool use.",
        "usemsg": "Tool choice set to none.",
        "config": {"type": "tool_choice", "value": "none"},
    },
    {
        "name": "🎲 Seed Setter",
        "price": 50000,
        "description": "Set a fixed seed for reproducible-ish responses. Pass the number as the `value` when you use it.",
        "usemsg": "Seed set.",
        "config": {"type": "seed", "mode": "prompt"},
    },
    {
        "name": "🧾 Stop Sequence Setter",
        "price": 50000,
        "description": "Set stop sequences (comma-separated). Pass them as the `value` when you use it.",
        "usemsg": "Stop sequences set.",
        "config": {"type": "stop_sequences", "mode": "prompt"},
    },
    {
        "name": "⚙️ Config Reset",
        "price": 100000,
        "description": "Reset all model configuration back to defaults (keeps a custom brain if one is set).",
        "usemsg": "All model configuration has been reset to defaults.",
        "config": {"type": "reset_all"},
    },
]

mainshop = [
    {
        "name": "🎁 Mystery Crate",
        "price": 20000,
        "description": "Crack it open for a random pile of coins. Sometimes a soggy sock.",
        "usemsg": "Crate opened.",
        "effect": "mystery_crate",
    },
    {
        "name": "🖨️ Money Printer",
        "price": 150000,
        "description": "Passive income: pays 30,000 coins/day for 7 days. Claim it with /bal.",
        "usemsg": "Money printer installed.",
        "effect": "money_printer",
    },
    {
        "name": "🛡️ Rob Insurance",
        "price": 25000,
        "description": "One-time shield: keeps your stake if a robbery fails.",
        "usemsg": "You're covered.",
        "effect": "rob_insurance",
    },
    {
        "name": "💹 Cringe Stocks",
        "price": 69420,
        "description": "The price fluctuates wildly every day. Buy low, sell high. Check the shop for today's price.",
        "usemsg": "You... threw it?",
        "stock": True,
        "stock_base": 69420,
    },
    {
        "name": "🏦 Interest Vault",
        "price": 300000,
        "description": "5% daily interest on your bank balance for 30 days. Claim it with /bal.",
        "usemsg": "Vault installed.",
        "effect": "interest_vault",
    },
    {
        "name": "📄 Job Contract",
        "price": 200000,
        "description": "Unlocks the /work command so you can earn coins on a cooldown.",
        "usemsg": "You're hired.",
        "effect": "job_contract",
    },
    {
        "name": "🎁 Gift Wrap",
        "price": 10000,
        "description": "Wrap one of your bag items and send it to someone. Use value:<@user> <item name>.",
        "usemsg": "Wrapped and sent.",
        "effect": "gift_wrap",
    },
]
